###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

  redis:
    image: redis:alpine
    container_name: sampler-books-redis

  mysql:
    image: mysql:5.7
    container_name: sampler-books-mysql
    working_dir: /application
    volumes:
      - .:/application
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sampler
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
    ports:
      - "8003:3306"

  webserver:
    image: nginx:alpine
    container_name: sampler-books-webserver
    working_dir: /application
    volumes:
      - .:/application
      - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "5000:80"

  php-fpm:
    build: phpdocker/php-fpm
    container_name: sampler-books-php-fpm
    working_dir: /application
    volumes:
      - .:/application
      - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini